### ISSUE TITLE
Release mechanisms for all components

### ISSUE THREAD

**Issue by Mierdin** [nre-learning/antidote#40]
Build basic test and release mechanism for all components. Then, switch ALL image references in all repos to a docker image tag, instead of `latest`.

Should also build a `dev` namespace, and a `prod` namespace. The former can use `latest`, so we can continue to see what the `latest` looks like, and then when we feel it's stable, we can run the release workflow to tag everything and update the `prod` namespace deployments.

See https://github.com/nre-learning/antidote-web/pull/5 for start on doing this in JS

# TODOs

- [x] Create PTR deployments 
- [x] Create Release Scripts
- [x] Create CHANGELOG files
- [x] Automate the update of PTR deployments on merges to master
- [x] Docs updates on all this
- [x] Would be nice if the web UI would contain commits for each project
- [x] Need to move everything out of the default namespace

# Release Workflow

- [x] Tag and push all docker images
- [x] Rotate CHANGELOG files
- [x] Tag all git repositories
