### ISSUE TITLE
Restructure antidote repo

### ISSUE THREAD

**Issue by Mierdin** [nre-learning/antidote#8]
> This issue was created as an overview of a large change to the structure of the project. While this is meant to make the long-term logistics of the project easier, it is a substantial change that all should be aware of, so please read the below carefully to ensure you're aware of the plan. This change is planned to be made in conjunction with, or just prior to, the v0.3.2 release (mid April '19)

Currently the antidote repo is a bit of a "junk drawer". It promotes confusion and conflation between the NRE Labs curriculum, the platform, and the infrastructure that happens to be in use to power our runtime of it.

Instead, the `antidote` repo should reflect the umbrella nature of the project; that is, it shouldn't contain much more than the `docs` directory, and a bunch of git submodules that point to other repos like `antidote-web`, and `syringe`. In addition, we should have a dedicated repo for the NRE Labs curriculum for two main reasons:

- This helps enforce the idea that NRE Labs is just that - a curriculum. That's it. The platform doesn't contain any curriculum-related materials, and nothing in what we refer to as NRE Labs is what actually makes the scheduling or web terminal work.
- This makes the curriculum less scary to contribute to. Rather than be inundated with references to infrastructure terraform files and platform kubernetes manifests, the only thing in the new NRE Labs repo will be NRE Labs curriculum materials.

This will prepare us for the long-term vision of the Antidote platform, and the NRE Labs curriculum, as separately maintained entities.

> The current release cadence, which keeps the version of the NRE Labs curriculum as well as that of the Antidote platform in sync, is not planned to change in the short term, but this restructuring opens up the possibility of maintaining an asynchronous release cycle for the curriculum vs the Antidote platform.

# Tasks

Here is the proposed order of tasks to accomplish this break-out:

- [x] The `antidote` repository will be renamed `nrelabs-curriculum`. This will ensure all history is preserved for all of the contributions to date.

> Existing pull requests, forks, branches, will continue to work, but contributors will need to update their remotes to point to the new repository name, since we'll be creating a new `antidote` repo in the next step

- [x] A new `antidote` repository will be created, and the `docs` directory will be moved from the `nrelabs-curriculum` repo into the new `antidote` repo.

- [x] The `infrastructure` and `platform` directories will be moved to [antidote-ops](https://github.com/nre-learning/antidote-ops)

- [x] Submodules to all component repositories, like `antidote-web` and `syringe` will be added to the `antidote` repository, and set to the latest released tag for each.

- [x] We'll go through all outstanding issues and make sure they get moved to the correct repository as necessary.

@nre-learning/community-managers
